flowchart LR
    User --> Register
    User --> LogIn

    subgraph ScooterApp
    Register --> LogIn
    LogIn --> removeScooter
    LogIn --> addScooter
    end

    subgraph Scooter
    removeScooter --> UndockScooter
    addScooter --> DockScooter
    end
